[package]
name = "chapter_19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "rust_fn"
#crate-type = ["cdylib"]  
crate-type = ["staticlib"]  
